### ISSUE TITLE
Curls on the left side of my part turn out wonky

### ISSUE THREAD

**Issue by vrk** [vrk/LearnToCurl#1]
I don't know where my arms are supposed to go on the left side?? Video tomorrow

**Comment by sssoleileraaa** [comment]
Maybe it's a curl direction issue?

You might be curling the left side in the same direction as the right. This would give you a different look on each side, and maybe you prefer something more symmetrical. Also, my grandma, who was a hair stylist, once told me that you should always curl away from the face. I think it makes the hair appear more wind blown, or something.

**Comment by vrk** [comment]
@creviera ooooh I bet it is!! OK, I will pay extra close attention to the direction I'm curling tomorrow and will report back. Also just throwing it out there, I would totally pair with your grandma (or you!!) on hair styling lol.

**Comment by vrk** [comment]
I THINK WE'VE RESOLVE THE ISSUE!! Today's left side curls have turned out much better <3
